### ISSUE TITLE
Tests. Like, yes, we should run them!

### ISSUE THREAD

**Issue by npostavs** [dimitri/el-get#1691]
#### Background

The travis CI test script, as of e868142, only reports the result of byte compilation. Before it attempted to run the scripts under `tests`, but failed because `ert` isn't installed in emacs 23.

#### TODO

- [ ] https://github.com/rolandwalker/emacs-travis has useful templates for emacs travis tests across several versions. https://github.com/rejeep/evm may be useful too. Incorporate one or both of these.
- [ ] It's better to have tests that don't rely on network access, for both reliability and speed. Possibly related: #969. 
- [ ] As mentioned in #739, the test names could be nicer (fix this along with previous point).
- [x] It would be good to somehow test the recipes themselves, at least applying `el-get-check-recipe`.
